# -*- coding: utf-8 -*-
"""
AI & Ancillary Sectors — company universe with qualitative research fields.
Source of universe: user-provided watchlist (64 rows, 4 duplicates removed -> 60 uniques).
Qualitative content is analyst-authored (knowledge as of early 2026) and is meant to be a
starting frame, not a substitute for primary filings. Quant fields are intentionally left
blank in the workbook for the user to populate.

Field key:
  sector   : workbook tab (Column A of source sheet)
  subind   : sub-industry (Column B of source sheet)
  name, ticker, exch, country, tag : from source sheet
  business : what they do + core revenue driver
  ai_role  : position in the AI value chain
  markets  : end-markets & demand drivers  (PRIORITY: markets)
  geo      : geographic revenue / country & geopolitical exposure  (PRIORITY: country)
  deals    : notable partnerships / M&A / supply contracts  (PRIORITY: deals)
  flows    : capital, capex, ownership & secular money flows  (PRIORITY: flows)
  moat     : durable advantage + main competitors
  risks    : key downside risks
  catalyst : near-term catalysts / watch items
  thesis   : one-line "why it matters"
  esg      : short ESG note
"""

COMPANIES = [
# ================= HARDWARE (17) =================
dict(sector="Hardware", subind="Foundry", name="TSMC", ticker="TSM", exch="NYSE / TWSE", country="Taiwan", tag="World's AI foundry",
 business="World's largest dedicated chip foundry; makes the leading-edge silicon (3nm/2nm) for nearly every AI chip designer. Revenue driven by wafer volume, node mix and pricing.",
 ai_role="The physical bottleneck of the AI build-out — fabricates NVIDIA, AMD, Broadcom, Apple and hyperscaler custom silicon plus advanced CoWoS packaging.",
 markets="HPC/AI now the largest revenue segment, overtaking smartphones; demand set by hyperscaler and GPU order books. Advanced packaging (CoWoS) capacity is the gating constraint.",
 geo="Manufacturing concentrated in Taiwan (geopolitical flashpoint); expanding fabs in Arizona, Japan (Kumamoto) and Germany. Revenue heavily US-customer weighted.",
 deals="Multi-year capacity agreements with NVIDIA/Apple; US CHIPS Act support for Arizona fabs; JV fabs (JASM) with Sony/Denso in Japan.",
 flows="Capex ~$40B+/yr — the single biggest tell for AI supply. Foreign institutional ownership high; ADR flows track AI sentiment.",
 moat="Multi-year process lead, unmatched yield/scale and packaging know-how. Rivals: Samsung Foundry, Intel Foundry — both trailing.",
 risks="Taiwan-China geopolitics; customer concentration; cyclical semi capex; export-control spillover.",
 catalyst="2nm ramp, CoWoS capacity adds, Arizona output, monthly sales prints, hyperscaler capex guides.",
 thesis="The indispensable chokepoint — no leading-edge AI chip ships without TSMC.",
 esg="High water/energy use in fabs; strong governance; renewable-energy commitments for fabs."),

dict(sector="Hardware", subind="Foundry", name="Samsung Electronics", ticker="005930", exch="KRX", country="South Korea", tag="Foundry + HBM",
 business="Diversified giant: memory (DRAM/NAND), foundry, smartphones and displays. Memory + foundry drive the AI angle.",
 ai_role="No.2 foundry and a key HBM supplier; qualifying HBM into NVIDIA is the swing factor for the AI story.",
 markets="AI server memory (HBM3E/HBM4), leading-edge foundry, plus consumer electronics cyclicality. Memory pricing is the dominant earnings lever.",
 geo="HQ Korea; fabs in Korea, US (Taylor, Texas) and China. Exposed to US-China export controls and Korea-China trade.",
 deals="US CHIPS Act funding for Taylor fab; HBM qualification agreements with AI GPU vendors; foundry deals for custom AI silicon.",
 flows="Massive memory capex cycle; large-cap index and Korea EM fund flows; buyback/dividend program supports the stock.",
 moat="Only vertically integrated memory+foundry+packaging player. Rivals: TSMC (foundry), SK Hynix/Micron (memory).",
 risks="HBM qualification delays vs SK Hynix; memory price swings; foundry losses; China exposure.",
 catalyst="HBM4 qualification at NVIDIA, memory price inflection, foundry customer wins, DRAM upcycle.",
 thesis="Cheapest way to play both AI memory and foundry — if HBM catch-up lands.",
 esg="Large emissions footprint; governance reforms ongoing; strong recycling/renewables targets."),

dict(sector="Hardware", subind="Foundry", name="Intel", ticker="INTC", exch="Nasdaq", country="USA", tag="US foundry",
 business="US chipmaker pivoting from IDM to foundry (IFS) while still selling client/data-center CPUs. Revenue split across products and nascent foundry.",
 ai_role="Aspiring third leading-edge foundry (18A/14A) and AI PC CPU vendor (Gaudi accelerators lag NVIDIA badly).",
 markets="PC and server CPUs (share losing to AMD/Arm), plus foundry ambitions. AI accelerator share is minimal.",
 geo="US-centric manufacturing — the flagship of US reshoring; fabs in Arizona, Ohio, Ireland, Israel. Largest CHIPS Act beneficiary.",
 deals="US government CHIPS funding and equity stake; foundry commitments from Microsoft/others; Brookfield/Apollo fab financing JVs.",
 flows="Heavy capex with external financing partners; dividend cut/suspension history; turnaround/value-fund ownership; government backing.",
 moat="US-based leading-edge capacity is strategically unique but execution-challenged. Rivals: TSMC, Samsung, AMD, Arm.",
 risks="Execution/yield risk on 18A; cash burn; CPU share loss; foundry customer traction unproven.",
 catalyst="18A ramp and external foundry wins, Panther Lake AI PC, balance-sheet/asset actions.",
 thesis="Deep-value turnaround and the only US-owned leading-edge foundry option — high risk, policy-supported.",
 esg="Strong climate targets; governance in flux amid restructuring; large US job creation."),

dict(sector="Hardware", subind="GPU", name="NVIDIA", ticker="NVDA", exch="Nasdaq", country="USA", tag="AI compute leader",
 business="Designs AI GPUs and the CUDA software platform; sells data-center systems (GPU + networking + software). Data-center revenue dominates.",
 ai_role="The center of gravity of the AI trade — GPUs + CUDA + NVLink + networking form the default AI training/inference stack.",
 markets="Hyperscaler and enterprise AI capex; sovereign AI; every AI model runs on or against NVIDIA. Demand gated by supply (TSMC/HBM).",
 geo="US-designed, TSMC-fabbed; huge exposure to China export controls (restricted SKUs). Sales skew US hyperscalers + growing sovereign buyers.",
 deals="Deep supply pacts with TSMC/SK Hynix; ecosystem tie-ins with all hyperscalers; investments across the AI startup stack (CoreWeave, model labs).",
 flows="Largest single beneficiary of AI capex flows; mega-cap index weight; capex commentary from MSFT/META/GOOGL/AMZN is the key tell.",
 moat="CUDA software lock-in + full-stack systems + pace of roadmap (Blackwell→Rubin). Rivals: AMD, Broadcom ASICs, hyperscaler in-house chips.",
 risks="Customer concentration; hyperscaler custom-silicon substitution; China restrictions; any AI-capex digestion.",
 catalyst="Blackwell/Rubin ramps, hyperscaler capex guides, HBM supply, China policy, new sovereign deals.",
 thesis="Owns the AI compute standard; earnings power scales with the entire industry's capex.",
 esg="Fabless (low direct footprint); scrutiny on end-use of chips; strong governance, founder-led."),

dict(sector="Hardware", subind="GPU", name="AMD", ticker="AMD", exch="Nasdaq", country="USA", tag="AI accelerators",
 business="Designs CPUs (EPYC/Ryzen) and AI GPUs (Instinct MI-series). Data-center CPU + AI GPU are the growth drivers.",
 ai_role="The credible No.2 AI accelerator; MI300/MI350 line is the main non-NVIDIA option hyperscalers are qualifying.",
 markets="Data-center AI GPUs and server CPUs (share gains vs Intel), plus PC/gaming/embedded. AI GPU ramp is the swing factor.",
 geo="US-designed, TSMC-fabbed; China export-control exposure on AI SKUs. Revenue diversified across US/EMEA/Asia.",
 deals="MI-series adoption at Microsoft/Meta/Oracle; ZT Systems acquisition for rack-scale systems; ROCm software push vs CUDA.",
 flows="Rides AI capex diversification (buyers wanting a second source); institutional accumulation on GPU wins.",
 moat="Chiplet design leadership and CPU share gains; weaker software (ROCm) vs CUDA. Rivals: NVIDIA, Intel, Arm.",
 risks="CUDA moat; GPU execution/software gaps; PC cyclicality; China limits.",
 catalyst="MI350/MI400 ramp, hyperscaler qualification wins, server CPU share, ROCm traction.",
 thesis="The default second source in AI compute with real CPU share momentum.",
 esg="Fabless; solid climate goals; strong governance."),

dict(sector="Hardware", subind="AI ASIC", name="Broadcom", ticker="AVGO", exch="Nasdaq", country="USA", tag="Custom AI chips",
 business="Semiconductors (networking, custom ASIC) + infrastructure software (VMware). AI custom silicon and networking chips drive the growth narrative.",
 ai_role="The pick-and-shovel of custom AI silicon — co-designs XPUs for Google (TPU), Meta and others, plus AI Ethernet/switch chips.",
 markets="Hyperscaler custom accelerators and AI networking; plus broad enterprise software (VMware). Custom-AI backlog is the key metric.",
 geo="US-designed, TSMC-fabbed; global enterprise software base. China exposure via networking.",
 deals="Multi-year XPU programs with hyperscalers; $69B VMware acquisition; long AI-revenue guidance targets.",
 flows="Dividend-growth + AI-optionality ownership; large-cap AI-adjacent flows; strong FCF funds buybacks/dividends.",
 moat="Best-in-class custom-ASIC design + networking IP + sticky software. Rivals: Marvell (ASIC), NVIDIA (networking), Arista.",
 risks="Customer concentration in custom AI; software integration; lumpy program timing; leverage.",
 catalyst="New XPU customer wins, AI revenue guide raises, VMware margins, next-gen switch silicon.",
 thesis="The prime beneficiary if hyperscalers build their own chips instead of buying NVIDIA.",
 esg="Fabless; strong FCF governance; leverage and integration scrutiny."),

dict(sector="Hardware", subind="Networking Silicon", name="Marvell", ticker="MRVL", exch="Nasdaq", country="USA", tag="AI interconnect",
 business="Data-infrastructure semis: custom AI silicon, optical DSPs, switching and storage connectivity. Data-center segment drives growth.",
 ai_role="Custom-ASIC challenger to Broadcom and a leader in optical interconnect (DSPs) that stitch AI clusters together.",
 markets="Hyperscaler custom compute and AI interconnect (optical/copper); carrier and enterprise as legacy drag.",
 geo="US-designed, TSMC-fabbed; global data-center customers; China exposure modest.",
 deals="Custom-silicon programs with hyperscalers (incl. Amazon); optical DSP design wins; multi-gen roadmap commitments.",
 flows="AI-interconnect thematic flows; smaller-cap volatility; institutional rotation on custom-silicon wins.",
 moat="Optical DSP leadership + custom-ASIC engineering. Rivals: Broadcom, NVIDIA networking, Coherent.",
 risks="Second in custom ASIC; program timing; legacy segment weakness; concentration.",
 catalyst="New custom-compute sockets, optical ramp, data-center revenue mix, guidance.",
 thesis="Levered play on AI cluster interconnect and the second-source ASIC trend.",
 esg="Fabless; standard governance; energy-efficiency positioning in interconnect."),

dict(sector="Hardware", subind="CPU", name="Arm Holdings", ticker="ARM", exch="Nasdaq", country="UK", tag="AI CPU architecture",
 business="Licenses CPU architecture and core designs; earns license fees + per-chip royalties. Royalty growth from higher-value designs drives the model.",
 ai_role="The instruction-set backbone increasingly used in data-center CPUs (Grace, Graviton, Axion) and every AI edge device.",
 markets="Smartphones (base), data-center CPUs, automotive and IoT/edge AI. Royalty per chip rising with compute-subsystem designs.",
 geo="UK-HQ, majority-owned by SoftBank; global licensees; China JV (Arm China) is a governance/geopolitical wildcard.",
 deals="Architecture in NVIDIA Grace, Amazon Graviton, Google Axion, Microsoft Cobalt; potential move toward selling own chiplets.",
 flows="High-multiple growth ownership; SoftBank float overhang; thematic AI-royalty flows.",
 moat="Ubiquitous, power-efficient architecture with enormous switching costs. Rivals: x86 (Intel/AMD), RISC-V.",
 risks="Rich valuation; RISC-V threat; Arm China control; SoftBank overhang.",
 catalyst="Data-center royalty ramp, v9 adoption, potential own-silicon strategy, licensing prints.",
 thesis="A royalty toll on nearly every chip, now expanding into the data center.",
 esg="IP-only footprint; governance complicated by SoftBank control + Arm China."),

dict(sector="Hardware", subind="Memory", name="SK Hynix", ticker="000660", exch="KRX", country="South Korea", tag="HBM leader",
 business="Memory maker (DRAM/NAND) that became the HBM leader. Earnings driven by memory pricing and HBM mix.",
 ai_role="The primary HBM supplier to NVIDIA — the memory that feeds AI GPUs; effectively sold out on HBM.",
 markets="AI server memory (HBM), plus conventional DRAM/NAND cyclicality. HBM is the highest-margin swing factor.",
 geo="HQ Korea; fabs in Korea and China (Wuxi); China exposure is an export-control risk. Sells into US AI supply chain.",
 deals="Preferred HBM supplier agreements with NVIDIA; capacity pre-sold years out; JV/packaging tie-ins.",
 flows="Memory upcycle capex; Korea EM + AI memory flows; leader-premium valuation vs peers.",
 moat="First-mover HBM yield/lead. Rivals: Samsung, Micron.",
 risks="HBM competition catching up; memory price cyclicality; China fab exposure.",
 catalyst="HBM4 ramp, pricing, capacity adds, NVIDIA order cadence, DRAM cycle.",
 thesis="Purest listed proxy for AI memory demand.",
 esg="High-energy fabs; renewables targets; governance improving."),

dict(sector="Hardware", subind="Memory", name="Micron", ticker="MU", exch="Nasdaq", country="USA", tag="HBM supplier",
 business="US memory maker (DRAM/NAND); the No.3 HBM supplier ramping into AI. Memory pricing + HBM mix drive earnings.",
 ai_role="The US-based HBM supplier diversifying the AI memory base away from Korea; HBM3E qualified into AI GPUs.",
 markets="AI/data-center memory (HBM), plus PC/mobile/auto DRAM cyclicality. HBM ramp is the growth lever.",
 geo="US-HQ with fabs in US/Asia; CHIPS Act support for US fabs; China sales restricted after security review.",
 deals="HBM supply into NVIDIA roadmap; US CHIPS funding for Idaho/New York fabs; long-term supply agreements.",
 flows="US-memory reshoring flows + AI memory thematic; cyclical value + growth crossover ownership.",
 moat="Only US-HQ leading memory maker; catching up on HBM. Rivals: SK Hynix, Samsung.",
 risks="Memory cyclicality; HBM share vs Korea; China revenue loss; capex intensity.",
 catalyst="HBM share gains, pricing inflection, US fab milestones, DRAM upcycle.",
 thesis="US-listed leverage to the AI memory upcycle with reshoring tailwinds.",
 esg="Energy-intensive fabs; strong US-jobs/climate positioning; solid governance."),

dict(sector="Hardware", subind="Equipment", name="ASML", ticker="ASML", exch="Euronext", country="Netherlands", tag="EUV monopoly",
 business="Sole maker of EUV lithography systems essential for leading-edge chips. Revenue from tool sales + high-margin service/installed base.",
 ai_role="The ultimate upstream monopoly — no advanced AI chip node exists without ASML's EUV/High-NA machines.",
 markets="Leading-edge logic (TSMC/Samsung/Intel) and advanced DRAM; demand tracks foundry/memory capex cycles.",
 geo="Netherlands-HQ; sells globally; China sales heavily restricted by Dutch/US export controls (a major swing factor).",
 deals="Long-lead EUV/High-NA orders from TSMC, Intel, Samsung; High-NA early shipments; deep supplier ecosystem (Zeiss).",
 flows="European large-cap + semi-cap capex flows; bookings ('net new orders') are the key sentiment gauge.",
 moat="Absolute EUV monopoly with a decade+ lead. Rivals: none in EUV; Canon/Nikon in older DUV.",
 risks="China export-control revenue hit; lumpy orders; foundry capex digestion; single-product concentration.",
 catalyst="Order bookings, High-NA adoption, China policy, TSMC/Intel capex plans.",
 thesis="The narrowest chokepoint in the entire AI supply chain.",
 esg="Strong governance and climate leadership; scrutiny on dual-use export controls."),

dict(sector="Hardware", subind="Equipment", name="Applied Materials", ticker="AMAT", exch="Nasdaq", country="USA", tag="Wafer equipment",
 business="Largest broad-line wafer-fab equipment (WFE) maker — deposition, etch, CMP, ion implant, plus service. Systems + services revenue.",
 ai_role="Sells the process tools that build every advanced logic and HBM/DRAM wafer for AI.",
 markets="Leading-edge logic, HBM/DRAM and advanced packaging capex; ICAPS (mature nodes) as ballast. WFE cycle drives revenue.",
 geo="US-HQ; large China revenue exposure (export-control sensitive); global fab customers.",
 deals="Tool supply to TSMC/Samsung/Intel/Micron; advanced-packaging and gate-all-around tool wins; R&D centers.",
 flows="Semi-cap capex cycle flows; dividend + buyback; China-exposure discount/premium swings.",
 moat="Breadth of WFE portfolio + materials-engineering IP + installed-base service. Rivals: Lam, TEL, KLA, ASML.",
 risks="China restrictions; WFE cyclicality; customer capex timing.",
 catalyst="Gate-all-around/HBM tool demand, China policy, WFE cycle turn, service growth.",
 thesis="Broadest picks-and-shovels exposure to AI-driven fab build-out.",
 esg="Materials/energy footprint; strong sustainability roadmap; solid governance."),

dict(sector="Hardware", subind="Equipment", name="Lam Research", ticker="LRCX", exch="Nasdaq", country="USA", tag="Chip fabrication",
 business="Leader in etch and deposition tools, especially for memory (3D NAND/DRAM) and advanced logic. Systems + service.",
 ai_role="Critical enabler of HBM/DRAM and advanced-logic scaling that AI memory and compute depend on.",
 markets="Memory capex (HBM/DRAM/NAND) and leading-edge logic; service/installed base as ballast.",
 geo="US-HQ; significant China revenue (export-control exposed); global memory/logic customers.",
 deals="Deep tool relationships with SK Hynix/Samsung/Micron/TSMC; advanced-packaging and etch roadmap wins.",
 flows="Memory-capex-levered flows; dividend + aggressive buyback; cyclical rotation.",
 moat="Etch/deposition leadership, strongest in memory. Rivals: AMAT, TEL, KLA.",
 risks="Memory cyclicality; China restrictions; concentration in memory capex.",
 catalyst="HBM/DRAM capex, NAND recovery, China policy, gate-all-around ramp.",
 thesis="Highest-beta equipment name to the AI memory build-out.",
 esg="Energy/chemistry footprint; strong governance; sustainability targets."),

dict(sector="Hardware", subind="Equipment", name="KLA", ticker="KLAC", exch="Nasdaq", country="USA", tag="Inspection",
 business="Dominates process control (inspection/metrology) — finds defects to protect yield. High-margin systems + service.",
 ai_role="Yield-critical at leading edge and in advanced packaging (CoWoS), where defect control gates AI-chip output.",
 markets="Leading-edge logic, memory and advanced packaging; process-control intensity rises with complexity.",
 geo="US-HQ; China revenue exposure; global foundry/memory customers.",
 deals="Process-control tool standard at TSMC/Samsung/Intel; packaging-inspection wins as CoWoS scales.",
 flows="Best-margin WFE name; dividend + buyback; quality-compounder ownership.",
 moat="~50%+ share of process control with huge data/algorithm lead. Rivals: AMAT (metrology), smaller players.",
 risks="China restrictions; WFE cyclicality; concentration.",
 catalyst="Advanced-packaging inspection demand, leading-edge ramp, China policy.",
 thesis="The highest-quality, highest-margin way to own rising chip complexity.",
 esg="Lower materials footprint than deposition/etch peers; strong governance."),

dict(sector="Hardware", subind="Equipment", name="Tokyo Electron", ticker="8035", exch="JPX", country="Japan", tag="Equipment leader",
 business="Japan's largest WFE maker — coater/developer, etch, deposition, cleaning. Systems + field service.",
 ai_role="Key process-tool supplier for advanced logic and HBM/DRAM feeding AI demand.",
 markets="Leading-edge logic and memory capex; coater/developer near-monopoly tied to lithography.",
 geo="Japan-HQ; large China revenue exposure; aligned with Japan's semi-policy revival.",
 deals="Tool supply to global foundries/memory makers; coater/developer paired with ASML litho; JV activity.",
 flows="Japan semiconductor/reflation flows; buyback/dividend; foreign-investor AI-capex interest.",
 moat="Coater/developer dominance + broad WFE line. Rivals: AMAT, Lam, KLA, SCREEN.",
 risks="China restrictions; WFE cyclicality; FX; concentration.",
 catalyst="WFE cycle, China policy, HBM capex, Japan-policy support.",
 thesis="Japan's core AI-capex equipment proxy with a coater/developer near-monopoly.",
 esg="Strong Japanese governance improvement; energy-efficiency focus."),

dict(sector="Hardware", subind="EDA", name="Synopsys", ticker="SNPS", exch="Nasdaq", country="USA", tag="Chip design software",
 business="Leading electronic design automation (EDA) software + IP for chip design; recurring/subscription revenue. Adding systems (Ansys).",
 ai_role="Every AI chip is designed in EDA tools; AI-assisted design (DSO.ai) and IP blocks accelerate the whole industry.",
 markets="Semiconductor and systems companies designing ever-more-complex AI chips; IP reuse rising.",
 geo="US-HQ; global design customers; China exposure a regulatory watch-item.",
 deals="$35B Ansys acquisition (multiphysics/simulation); deep tool partnerships with TSMC/foundries and every chip designer.",
 flows="Sticky software recurring revenue; quality-compounder ownership; index/software flows.",
 moat="EDA duopoly with Cadence; enormous switching costs + IP library. Rivals: Cadence, Siemens EDA.",
 risks="Ansys integration; China regulatory; design-activity slowdown; valuation.",
 catalyst="Ansys close/synergies, AI-design adoption, chip-design starts, IP growth.",
 thesis="A recurring-revenue toll on the complexity of every AI chip designed.",
 esg="Software footprint; strong governance; talent-driven."),

dict(sector="Hardware", subind="EDA", name="Cadence", ticker="CDNS", exch="Nasdaq", country="USA", tag="Chip design software",
 business="EDA software, IP and simulation for chip and system design; recurring revenue model. Expanding into system design/biology.",
 ai_role="Co-leader of the EDA tools that design AI silicon; AI-driven design optimization and hardware emulation.",
 markets="Chip designers and, increasingly, system/3D-IC and multiphysics customers. Design complexity drives demand.",
 geo="US-HQ; global customers; China a regulatory watch-item.",
 deals="Emulation/prototyping wins with hyperscalers; partnerships across foundries; tuck-in acquisitions in system design.",
 flows="High-quality recurring software flows; premium multiple; software-index ownership.",
 moat="EDA duopoly with Synopsys; deep tool lock-in. Rivals: Synopsys, Siemens EDA.",
 risks="China regulatory; valuation; design-cycle sensitivity.",
 catalyst="AI-design adoption, emulation demand, 3D-IC growth, bookings.",
 thesis="The other half of the EDA duopoly powering AI chip design.",
 esg="Software footprint; strong governance."),

# ================= INFRASTRUCTURE (17) =================
dict(sector="Infrastructure", subind="Cloud", name="Microsoft", ticker="MSFT", exch="Nasdaq", country="USA", tag="Azure AI",
 business="Enterprise software + Azure cloud + Office/Windows + gaming. Azure and Copilot monetization drive the AI narrative.",
 ai_role="Frontier-model distribution leader via OpenAI partnership; Azure AI + Copilot embed AI across the enterprise stack.",
 markets="Enterprise cloud, productivity software, security and gaming; AI capacity demand outstripping supply.",
 geo="Global; US-centric revenue with large EMEA/Asia; data-center build-out worldwide (incl. sovereign clouds).",
 deals="~$13B+ OpenAI investment/partnership; massive GPU purchases from NVIDIA/AMD; global data-center leases.",
 flows="Mega-cap index anchor; among the largest AI capex spenders (a key demand tell); huge buyback + dividend.",
 moat="Enterprise distribution, install base and OpenAI access. Rivals: Google, Amazon, Salesforce.",
 risks="AI capex ROI scrutiny; OpenAI relationship dynamics; regulatory; capacity constraints.",
 catalyst="Azure growth, Copilot monetization, capex guides, OpenAI developments.",
 thesis="The enterprise on-ramp to frontier AI with the distribution to monetize it.",
 esg="Carbon-negative pledge strained by data-center growth; strong governance."),

dict(sector="Infrastructure", subind="Cloud", name="Amazon", ticker="AMZN", exch="Nasdaq", country="USA", tag="AWS",
 business="E-commerce + AWS cloud + advertising. AWS is the profit engine and the AI infrastructure play.",
 ai_role="Largest cloud (AWS) with custom AI silicon (Trainium/Inferentia) and Bedrock model platform; Anthropic partner.",
 markets="Enterprise cloud, retail, ads and devices; AI infrastructure demand accelerating AWS.",
 geo="Global; US-heavy revenue; data-center regions worldwide including sovereign build-outs.",
 deals="Multi-billion Anthropic investment; Trainium/Inferentia custom silicon (with Marvell/Annapurna); vast data-center capex.",
 flows="Mega-cap AI capex spender; retail-margin + AWS-growth ownership; index anchor.",
 moat="AWS scale + custom silicon + retail flywheel. Rivals: Microsoft, Google, Alibaba.",
 risks="Capex ROI; retail margin cyclicality; regulatory; AWS growth deceleration.",
 catalyst="AWS reacceleration, Trainium adoption, Anthropic/Bedrock traction, capex.",
 thesis="Cloud scale leader building its own AI silicon to protect margins.",
 esg="Climate Pledge; labor scrutiny; strong founder-influenced governance."),

dict(sector="Infrastructure", subind="Cloud", name="Alphabet", ticker="GOOGL", exch="Nasdaq", country="USA", tag="Google Cloud + Gemini",
 business="Search/advertising + Google Cloud + YouTube + Other Bets. Ads fund the AI build-out; Cloud is the growth+AI vector.",
 ai_role="Full-stack AI: Gemini frontier models, TPUs (custom silicon via Broadcom), DeepMind research, and AI-infused Search/Cloud.",
 markets="Digital advertising, enterprise cloud, and consumer AI; AI reshaping search monetization.",
 geo="Global; US-heavy ad revenue; worldwide data centers and subsea infrastructure.",
 deals="TPU co-design with Broadcom; Cloud AI deals; large data-center and energy (nuclear/PPA) agreements.",
 flows="Mega-cap AI capex spender; ad-cashflow + cloud-growth ownership; buyback + new dividend.",
 moat="Own models + own silicon (TPU) + distribution (Search/Android/YouTube). Rivals: Microsoft/OpenAI, Amazon.",
 risks="Search disruption by AI; antitrust/regulatory; capex ROI.",
 catalyst="Gemini adoption, Cloud margins, TPU scale, AI-search monetization, antitrust rulings.",
 thesis="The only Big Tech player owning models, silicon and distribution end-to-end.",
 esg="24/7 carbon-free energy goal pressured by AI; antitrust governance overhang."),

dict(sector="Infrastructure", subind="Cloud", name="Oracle", ticker="ORCL", exch="NYSE", country="USA", tag="OCI AI",
 business="Enterprise database + applications + OCI cloud infrastructure. OCI AI-capacity growth drives the re-rating.",
 ai_role="Fast-growing AI cloud (OCI) renting GPU capacity; became a favored home for AI training workloads and model labs.",
 markets="Enterprise database/apps and, increasingly, GPU cloud capacity; RPO backlog signals AI demand.",
 geo="Global; US-heavy; expanding sovereign and multicloud data-center regions.",
 deals="Large multi-billion GPU-cloud contracts (incl. OpenAI/Stargate-linked capacity); multicloud deals with Microsoft/Google.",
 flows="Huge RPO/backlog + rising capex; re-rating on AI-cloud flows; dividend + buyback.",
 moat="Enterprise database lock-in + aggressive OCI pricing/performance. Rivals: AWS, Azure, Google Cloud.",
 risks="Capex-funded growth/leverage; customer concentration; execution on capacity.",
 catalyst="RPO/backlog prints, OCI capacity ramp, big AI-contract announcements, margins.",
 thesis="The database incumbent reinventing itself as a hyperscale AI-capacity provider.",
 esg="Data-center energy scrutiny; founder-influenced governance."),

dict(sector="Infrastructure", subind="Cloud", name="Alibaba", ticker="BABA", exch="NYSE / HKEX", country="China", tag="China cloud leader",
 business="China e-commerce + Alibaba Cloud + logistics/media. Cloud and AI (Qwen models) are the strategic pivot.",
 ai_role="China's leading cloud with open Qwen models; the key AI-infrastructure play inside China's walled market.",
 markets="China commerce, enterprise cloud and international commerce; domestic AI capex ramping.",
 geo="China-centric (regulatory/geopolitical risk); ADR + HK listing; US-China tension and delisting risk.",
 deals="Large domestic AI-cloud capex commitments; Qwen open-model ecosystem; restructuring/spin plans.",
 flows="China-stimulus + AI-capex flows; deep-value + buyback story; ADR/southbound flows.",
 moat="China cloud scale + Qwen models + commerce data. Rivals: Tencent, Huawei, ByteDance.",
 risks="China regulation, macro, US-China tension, delisting, competition.",
 catalyst="China AI capex, cloud reacceleration, Qwen adoption, stimulus, buybacks.",
 thesis="The cheapest large-cap way to own China's AI-infrastructure build-out.",
 esg="Governance/VIE-structure risk; state-policy exposure; improving disclosure."),

dict(sector="Infrastructure", subind="Cloud", name="Tencent", ticker="000700", exch="HKEX", country="China", tag="AI ecosystem",
 business="China's social/gaming/fintech super-app (WeChat) + cloud. AI (Hunyuan) infused across gaming, ads and cloud.",
 ai_role="Deploys AI across the largest China consumer ecosystem; Hunyuan models + AI-boosted ads and gaming.",
 markets="Gaming, social advertising, fintech and cloud; AI lifting ad targeting and content.",
 geo="China-centric; HK listing; regulatory and US-China tech-tension exposure.",
 deals="Domestic AI investments and model development; global gaming stakes; cloud/enterprise AI push.",
 flows="China consumer-recovery + AI flows; large buyback; southbound/HK flows.",
 moat="WeChat ecosystem lock-in + gaming IP + data. Rivals: Alibaba, ByteDance, NetEase.",
 risks="China gaming/ad regulation, macro, geopolitics.",
 catalyst="Ad growth from AI, gaming pipeline, cloud AI, buyback pace.",
 thesis="AI monetized across the deepest consumer ecosystem in China.",
 esg="Governance/state-policy risk; content-regulation exposure."),

dict(sector="Infrastructure", subind="Data Centers", name="Equinix", ticker="EQIX", exch="Nasdaq", country="USA", tag="Global colocation",
 business="Global colocation/interconnection REIT; rents data-center space and network exchange. Recurring rental + interconnection revenue.",
 ai_role="Neutral meeting point where enterprises, clouds and networks interconnect for AI/hybrid workloads; adding AI-ready capacity.",
 markets="Enterprise hybrid cloud, network/cloud interconnection and (new) AI training/inference colocation.",
 geo="Truly global footprint (Americas/EMEA/APAC); diversified country exposure.",
 deals="xScale JVs (with GIC/others) for hyperscale capacity; power-procurement and AI-colocation offerings.",
 flows="REIT income + AI-growth flows; large capex build cycle; dividend growth.",
 moat="Densest global interconnection fabric (network effect). Rivals: Digital Realty, hyperscalers' own DCs.",
 risks="Power availability, capex/rates, AI-colo economics vs hyperscale self-build.",
 catalyst="AI capacity bookings, xScale JV expansion, power deals, bookings/churn.",
 thesis="The interconnection backbone benefiting from AI-driven data gravity.",
 esg="Aggressive renewable/PPA program; strong REIT governance."),

dict(sector="Infrastructure", subind="Data Centers", name="Digital Realty", ticker="DLR", exch="NYSE", country="USA", tag="AI data centers",
 business="Global data-center REIT spanning hyperscale to colocation. Recurring leases; hyperscale AI capacity is the growth driver.",
 ai_role="Landlord to hyperscalers building AI clusters; leases large power-dense capacity for training/inference.",
 markets="Hyperscale cloud/AI leasing and enterprise colocation; power-dense AI demand.",
 geo="Global (Americas/EMEA/APAC); diversified via PlatformDIGITAL and JVs.",
 deals="Development JVs (Blackstone, GI Partners) to fund hyperscale build; large hyperscaler leases.",
 flows="REIT income + AI-leasing flows; capital-recycling via JVs; dividend.",
 moat="Global scale + land/power bank. Rivals: Equinix, hyperscaler self-build, private DC developers.",
 risks="Power/grid constraints, funding cost, hyperscaler self-build, leverage.",
 catalyst="Record leasing signings, power procurement, JV funding, backlog.",
 thesis="Direct REIT exposure to hyperscale AI capacity leasing.",
 esg="Renewable procurement leader; REIT governance."),

dict(sector="Infrastructure", subind="Data Centers", name="NextDC", ticker="NXT", exch="ASX", country="Australia", tag="APAC exposure",
 business="Australian data-center developer/operator building hyperscale + AI-ready capacity. Contracted capacity (MW) drives value.",
 ai_role="APAC AI-capacity play; building high-density campuses for hyperscalers and AI workloads across Australia/Asia.",
 markets="Hyperscale cloud and AI colocation in Australia and expanding into Asia (Malaysia, NZ, Japan).",
 geo="Australia-centric with APAC expansion; sovereign/regional data-sovereignty tailwind.",
 deals="Hyperscaler contracts; capital raises to fund campuses; regional expansion sites.",
 flows="Growth-capex heavy; equity raises; ASX growth + AI-infrastructure flows.",
 moat="Leading independent AU data-center platform + land/power. Rivals: AirTrunk, Equinix, hyperscalers.",
 risks="Funding dilution, power/grid, execution, contract timing.",
 catalyst="New contracted MW, Asia expansion, capital raises, hyperscaler wins.",
 thesis="Pure APAC exposure to the data-center/AI capacity build-out.",
 esg="Renewable-powered design focus; ASX governance standards."),

dict(sector="Infrastructure", subind="Data Centers", name="Keppel DC REIT", ticker="AJBU", exch="SGX", country="Singapore", tag="Southeast Asia exposure",
 business="Singapore-listed data-center REIT owning colocation assets across Asia-Pacific and Europe. Rental income REIT.",
 ai_role="Income-oriented exposure to data-center demand (incl. AI tailwinds) via a diversified DC property portfolio.",
 markets="Colocation leasing to cloud/enterprise tenants; AI demand supports occupancy/rents.",
 geo="Singapore-anchored with APAC + Europe assets; SE-Asia data-sovereignty tailwind.",
 deals="Asset acquisitions from sponsor (Keppel) pipeline; AI/DC capacity additions.",
 flows="REIT yield + rate-sensitivity flows; SGX income ownership; sponsor pipeline.",
 moat="Sponsor pipeline + Asia DC footprint. Rivals: other DC REITs, private operators.",
 risks="Rates, tenant concentration, one client-default history, FX.",
 catalyst="Acquisitions, rent reversions, occupancy, rate path.",
 thesis="Yield-focused way to own Asian data-center demand.",
 esg="Green-certified assets; REIT governance under Keppel."),

dict(sector="Infrastructure", subind="Servers", name="Super Micro Computer", ticker="SMCI", exch="Nasdaq", country="USA", tag="AI server leader",
 business="Builds high-performance servers and storage, specializing in GPU/AI systems with liquid cooling. Hardware revenue, thin margins.",
 ai_role="First-to-market integrator of NVIDIA/AMD GPU servers and rack-scale AI systems with direct-liquid-cooling.",
 markets="AI training/inference servers for hyperscalers, neoclouds and enterprises; demand gated by GPU supply.",
 geo="US-HQ with manufacturing in US/Taiwan/Malaysia; global customers.",
 deals="Close NVIDIA/AMD allocation ties; large neocloud/enterprise orders; capacity expansion.",
 flows="High-beta AI-server flows; volatile ownership after accounting/governance episodes; capex-for-capacity.",
 moat="Speed-to-market + liquid-cooling design + configurability. Rivals: Dell, HPE, Foxconn, Quanta.",
 risks="Governance/accounting history, thin margins, GPU allocation, competition, working-capital swings.",
 catalyst="Revenue growth, margin trajectory, liquid-cooling ramp, filing/governance clarity.",
 thesis="Highest-beta pure-play on AI server shipments — with governance caveats.",
 esg="Governance concerns (audit/filing history) are the key ESG flag; energy-efficient cooling positive."),

dict(sector="Infrastructure", subind="Servers", name="Dell Technologies", ticker="DELL", exch="NYSE", country="USA", tag="Enterprise AI servers",
 business="PCs + enterprise infrastructure (servers/storage). AI-optimized servers (ISG) drive the growth story; PCs are the base.",
 ai_role="Scaled enterprise/AI server vendor shipping NVIDIA-based systems with services and financing to enterprises.",
 markets="Enterprise/hyperscaler AI servers, storage, and commercial PCs (AI-PC refresh optionality).",
 geo="Global; US-heavy; manufacturing across US/Asia/Mexico.",
 deals="Large AI-server backlog with NVIDIA silicon; big enterprise/neocloud wins (e.g., xAI-type deals); financing arm.",
 flows="AI-server backlog + PC-recovery flows; dividend + buyback; value + growth crossover.",
 moat="Scale, supply chain, enterprise relationships + services/financing. Rivals: Supermicro, HPE, Lenovo.",
 risks="Thin server margins, PC cyclicality, GPU allocation, competition.",
 catalyst="AI-server backlog conversion, margins, AI-PC cycle, ISG growth.",
 thesis="The enterprise-grade, better-governed alternative to Supermicro in AI servers.",
 esg="Recycling/circular programs; solid governance."),

dict(sector="Infrastructure", subind="Servers", name="Hon Hai (Foxconn)", ticker="002317", exch="TWSE", country="Taiwan", tag="AI server manufacturing",
 business="World's largest electronics contract manufacturer (iPhone assembler) diversifying into AI servers/EV. AI-server assembly is the new growth leg.",
 ai_role="Largest ODM/assembler of AI server racks (incl. NVIDIA GB-series systems) for hyperscalers and cloud vendors.",
 markets="AI server/rack assembly, consumer electronics (Apple), plus EV/components ambitions.",
 geo="Taiwan-HQ with vast China manufacturing + diversifying to Mexico/US/India/SE-Asia (China+1).",
 deals="NVIDIA GB200/rack-scale manufacturing; hyperscaler ODM contracts; US/Mexico AI-server capacity.",
 flows="Taiwan large-cap + AI-supply-chain flows; margin-mix shift toward higher-value servers; dividend.",
 moat="Unmatched manufacturing scale + integration speed. Rivals: Quanta, Wistron/Wiwynn, Inventec.",
 risks="Thin margins, Apple concentration, China exposure, geopolitics.",
 catalyst="AI-server revenue mix, GB-rack ramp, margin improvement, capacity diversification.",
 thesis="The manufacturing backbone turning GPUs into deployed AI racks.",
 esg="Labor-practice scrutiny (large workforce); improving governance/disclosure."),

dict(sector="Infrastructure", subind="Power", name="Vertiv", ticker="VRT", exch="NYSE", country="USA", tag="AI cooling",
 business="Data-center critical infrastructure: power (UPS/switchgear), thermal management and liquid cooling. Product + service revenue.",
 ai_role="Prime beneficiary of AI power density — supplies the cooling and power gear every AI data center needs.",
 markets="Hyperscale/colo data centers; AI-driven power density lifting thermal (liquid-cooling) demand sharply.",
 geo="Global; Americas-heavy; manufacturing footprint worldwide.",
 deals="NVIDIA reference-architecture collaboration on cooling/power; large hyperscaler orders; backlog build.",
 flows="AI-infrastructure momentum flows; rising backlog/book-to-bill; multiple re-rating.",
 moat="Broad power+thermal portfolio + service network + liquid-cooling lead. Rivals: Schneider, Eaton, nVent.",
 risks="Data-center capex cyclicality, competition, supply chain, valuation.",
 catalyst="Orders/book-to-bill, liquid-cooling adoption, backlog, hyperscaler capex.",
 thesis="The clearest arms-dealer to AI power and cooling demand.",
 esg="Efficiency products aid customer sustainability; solid governance."),

dict(sector="Infrastructure", subind="Power", name="Schneider Electric", ticker="SU", exch="Euronext", country="France", tag="Electrical infrastructure",
 business="Global leader in electrical distribution + energy management + industrial automation. Products + software (AVEVA) + services.",
 ai_role="Supplies the electrical backbone (switchgear, busway, power management, prefab modular DC) for AI data centers.",
 markets="Data centers, buildings, industry and grid; electrification + AI-power demand as structural drivers.",
 geo="Global (Europe/North America/Asia balanced); broad country diversification.",
 deals="Data-center partnerships (incl. NVIDIA reference designs); AVEVA software; modular DC and grid deals.",
 flows="European large-cap electrification/AI-power flows; steady dividend; quality-compounder ownership.",
 moat="Breadth + software + global scale in electrical infra. Rivals: Eaton, ABB, Siemens, Vertiv.",
 risks="Industrial cyclicality, FX, competition, macro Europe.",
 catalyst="Data-center bookings, electrification capex, AVEVA growth, margins.",
 thesis="Diversified blue-chip play on electrification and AI-power infrastructure.",
 esg="Consistently rated among most sustainable firms; strong governance."),

dict(sector="Infrastructure", subind="Power", name="Eaton", ticker="ETN", exch="NYSE", country="Ireland", tag="Grid & power",
 business="Power-management company: electrical products/systems + aerospace/vehicle. Electrical segment drives AI exposure.",
 ai_role="Supplies grid-to-chip power infrastructure (switchgear, UPS, transformers) for data centers and utilities.",
 markets="Data centers, utilities/grid, industrial and aerospace; electrification megaproject backlog.",
 geo="Irish-domiciled, US-listed; Americas-heavy revenue; global operations.",
 deals="Data-center power orders; utility/grid modernization; capacity expansions; tuck-in M&A.",
 flows="Electrification/AI-power thematic flows; record backlog; dividend-growth ownership.",
 moat="Scale + backlog + electrical-systems breadth. Rivals: Schneider, ABB, Vertiv, GE Vernova.",
 risks="Cyclicality, supply chain, competition, valuation.",
 catalyst="Backlog/orders, data-center + grid capex, margins, mega-project pipeline.",
 thesis="Grid-and-power picks-and-shovels for the AI + electrification build-out.",
 esg="Electrification enabler; strong safety/governance record."),

dict(sector="Infrastructure", subind="Power", name="ABB", ticker="ABB", exch="SIX", country="Switzerland", tag="Grid automation",
 business="Electrification + automation + robotics + motion. Electrification and automation feed data-center and industrial AI.",
 ai_role="Provides power distribution, cooling and automation for data centers plus factory automation/robotics.",
 markets="Data centers, utilities, process/discrete industry and buildings; electrification + automation drivers.",
 geo="Swiss-HQ; globally diversified (Europe/Americas/Asia); planning robotics unit separation.",
 deals="Data-center electrification orders; robotics spin-off plans; automation partnerships.",
 flows="European industrial + electrification flows; buyback + dividend; portfolio-simplification story.",
 moat="Electrification + automation breadth + installed base. Rivals: Schneider, Siemens, Eaton, Rockwell.",
 risks="Industrial cyclicality, FX, execution on spin-offs.",
 catalyst="Data-center orders, robotics spin, margin expansion, order intake.",
 thesis="Electrification + automation exposure with a robotics-separation catalyst.",
 esg="Strong sustainability positioning; Swiss governance standards."),

# ================= NETWORKING (3) =================
dict(sector="Networking", subind="Networking", name="Arista Networks", ticker="ANET", exch="NYSE", country="USA", tag="AI networking",
 business="High-speed data-center switching (hardware + EOS software). Cloud/AI Ethernet networking drives revenue.",
 ai_role="Leading Ethernet fabric for AI/back-end networks connecting GPU clusters at scale (vs InfiniBand).",
 markets="Hyperscaler/cloud and enterprise data-center networking; AI back-end Ethernet is the growth vector.",
 geo="US-HQ; hyperscaler-concentrated revenue; global enterprise base.",
 deals="Deep ties with Microsoft/Meta (large customers); Ultra Ethernet ecosystem; AI-cluster design wins.",
 flows="AI-networking thematic flows; customer-concentration sensitivity; buyback.",
 moat="EOS software quality + merchant-silicon flexibility. Rivals: NVIDIA (InfiniBand/Spectrum), Cisco, Broadcom.",
 risks="Customer concentration (few hyperscalers), NVIDIA competition, capex cyclicality.",
 catalyst="AI back-end Ethernet wins, hyperscaler capex, guidance, 800G ramp.",
 thesis="The Ethernet standard-bearer for connecting AI clusters.",
 esg="Software-led efficiency; solid governance."),

dict(sector="Networking", subind="Optical", name="Coherent", ticker="COHR", exch="NYSE", country="USA", tag="Optical connectivity",
 business="Photonics/optics + materials: optical transceivers, lasers, compound semis. Datacom transceivers drive the AI story.",
 ai_role="Supplies high-speed optical transceivers (800G/1.6T) that carry data between AI GPUs/switches.",
 markets="AI data-center interconnect (datacom), telecom, industrial lasers and materials.",
 geo="US-HQ with global (incl. China) manufacturing; supply-chain diversification underway.",
 deals="Transceiver supply into hyperscaler AI clusters; indium-phosphide/laser capacity expansion; deleveraging.",
 flows="AI-optics thematic flows; deleveraging + turnaround ownership; higher-beta.",
 moat="Vertical integration in lasers/materials + transceiver scale. Rivals: Lumentum, Marvell (DSP), Chinese optics.",
 risks="Leverage, China exposure, transceiver pricing/competition, cyclicality.",
 catalyst="800G/1.6T ramp, datacom growth, margin/deleveraging progress.",
 thesis="Levered play on exploding AI optical-interconnect bandwidth.",
 esg="Manufacturing footprint; improving governance post-integration."),

dict(sector="Networking", subind="Optical", name="Celestica", ticker="CLS", exch="TSX / NYSE", country="Canada", tag="AI networking hardware",
 business="Electronics manufacturing services (EMS) + hardware platform solutions. Hyperscaler networking/AI hardware drives growth.",
 ai_role="Designs/builds custom networking switches and AI server hardware for hyperscalers (CCS segment).",
 markets="Hyperscaler networking/compute hardware, plus aerospace/industrial/health EMS.",
 geo="Canada-HQ; global manufacturing (Asia/Americas/Europe); hyperscaler-concentrated growth.",
 deals="Custom-switch and AI-hardware programs with large cloud customers; capacity for 800G platforms.",
 flows="AI-hardware re-rating flows; smaller-cap momentum; buyback.",
 moat="Design + manufacturing for hyperscaler custom hardware. Rivals: Foxconn, Jabil, Flex, Quanta.",
 risks="Customer concentration, thin EMS margins, program timing, cyclicality.",
 catalyst="CCS/hyperscaler program ramps, 800G, guidance raises, margins.",
 thesis="Under-the-radar EMS beneficiary of custom AI-networking hardware.",
 esg="EMS footprint; solid governance."),

# ================= SOFTWARE (9) =================
dict(sector="Software", subind="Foundation AI", name="Meta Platforms", ticker="META", exch="Nasdaq", country="USA", tag="Llama",
 business="Social platforms (Facebook/Instagram/WhatsApp) monetized via advertising. Ads fund AI; Llama models + AI-ranked feeds/ads.",
 ai_role="Leading open-weight model developer (Llama); AI drives ad targeting, content ranking and (long-term) assistants/hardware.",
 markets="Digital advertising (core), plus Reality Labs/AI hardware bets; AI lifting ad performance.",
 geo="Global user base; US/Europe ad revenue heavy; data centers worldwide; EU regulatory exposure.",
 deals="Massive GPU purchases (NVIDIA); custom silicon (MTIA); huge data-center + energy deals; open-Llama ecosystem.",
 flows="Mega-cap AI capex spender (a key demand tell); ad-cashflow + buyback + dividend ownership.",
 moat="Network effects + ad-targeting data + open-model ecosystem. Rivals: Google, TikTok, OpenAI.",
 risks="AI capex ROI/Reality Labs losses, ad cyclicality, EU/antitrust regulation.",
 catalyst="Ad growth from AI, capex guides, Llama adoption, AI-assistant/hardware traction.",
 thesis="Ad cash machine funding one of the largest AI compute build-outs, open-model leader.",
 esg="Content/privacy governance scrutiny; renewable-energy commitments for data centers."),

dict(sector="Software", subind="Enterprise AI", name="Palantir", ticker="PLTR", exch="Nasdaq", country="USA", tag="Enterprise AI platform",
 business="Data/AI operating platforms (Gotham for gov, Foundry for commercial, AIP for LLM ops). Software + deployment revenue.",
 ai_role="Turns enterprise/government data into operational AI applications; AIP is the LLM-orchestration land-grab.",
 markets="US government/defense and US commercial enterprises adopting AI ops; bootcamp-driven land-and-expand.",
 geo="US-heavy (gov + commercial); selective allied-government international; limited China.",
 deals="Large US defense/agency contracts; commercial AIP expansions; ecosystem partnerships.",
 flows="High-multiple momentum ownership; retail + index inclusion flows; volatile.",
 moat="Deep data-integration/ontology + government trust + AIP speed. Rivals: hyperscalers, Snowflake/Databricks, in-house.",
 risks="Very rich valuation, gov-contract lumpiness, stock-based comp, competition.",
 catalyst="US commercial growth, AIP deal counts, government awards, margin/RPO.",
 thesis="Front-runner in operationalizing AI for enterprises and government — at a demanding price.",
 esg="Government/defense-use ethics scrutiny; founder-controlled governance."),

dict(sector="Software", subind="Enterprise AI", name="Snowflake", ticker="SNOW", exch="NYSE", country="USA", tag="AI data cloud",
 business="Cloud data platform (warehouse/lakehouse) with consumption-based revenue. AI/ML (Cortex) drives new workloads.",
 ai_role="The data foundation for enterprise AI — where governed data lives for training/RAG; Cortex adds LLM features.",
 markets="Enterprise data analytics + AI; consumption model tied to data/AI workload growth.",
 geo="US-heavy; global enterprise expansion; runs atop AWS/Azure/GCP.",
 deals="LLM/model partnerships (incl. Anthropic/Mistral in-platform); acquisitions in AI/data; marketplace.",
 flows="Consumption-revenue + NRR-driven ownership; growth-software flows; buyback.",
 moat="Ease-of-use + data-sharing network + cross-cloud. Rivals: Databricks, hyperscaler data services, BigQuery.",
 risks="Databricks competition, consumption softness, valuation, hyperscaler encroachment.",
 catalyst="Cortex/AI workload adoption, NRR, product velocity, consumption trends.",
 thesis="The neutral data layer that enterprise AI is built on top of.",
 esg="Software footprint; standard governance."),

dict(sector="Software", subind="Enterprise AI", name="ServiceNow", ticker="NOW", exch="NYSE", country="USA", tag="AI workflows",
 business="Enterprise workflow/automation platform (ITSM and beyond) with subscription revenue. GenAI (Now Assist) drives upsell.",
 ai_role="Embeds agentic AI into enterprise workflows (IT, HR, customer, security); a top enterprise-AI monetizer.",
 markets="Large-enterprise digital workflow/automation; AI upsell expanding deal sizes.",
 geo="Global; US-heavy; strong regulated-industry and government presence.",
 deals="AI partnerships (NVIDIA, hyperscalers, model providers); Now Assist expansions; tuck-in AI acquisitions.",
 flows="High-quality SaaS compounder flows; premium multiple; institutional core-holding.",
 moat="Platform stickiness + workflow system-of-record. Rivals: Salesforce, Microsoft, SAP.",
 risks="Rich valuation, macro IT budgets, competition, AI-ROI proof.",
 catalyst="Now Assist/Pro Plus attach, cRPO growth, agentic-AI wins, guidance.",
 thesis="Best-in-class SaaS platform turning enterprise AI into measurable workflow ROI.",
 esg="Strong governance/ESG ratings; software footprint."),

dict(sector="Software", subind="Enterprise AI", name="Salesforce", ticker="CRM", exch="NYSE", country="USA", tag="Agentic AI",
 business="Enterprise CRM + platform (Sales/Service/Marketing/Data Cloud/Slack). Subscription revenue; Agentforce is the AI bet.",
 ai_role="Pushing agentic AI (Agentforce) on top of CRM + Data Cloud to automate customer-facing work.",
 markets="Enterprise CRM/customer engagement; AI agents as a new consumption/seat driver.",
 geo="Global; US-heavy; broad enterprise base.",
 deals="Agentforce launches; Data Cloud + partner ecosystem; acquisitions (e.g., Informatica-type data assets).",
 flows="Large-cap SaaS + margin-expansion flows; dividend + buyback; value-meets-growth.",
 moat="CRM incumbency + data + ecosystem. Rivals: Microsoft, ServiceNow, HubSpot, SAP.",
 risks="Agentforce monetization proof, seat-model disruption by AI, macro, competition.",
 catalyst="Agentforce adoption/consumption, Data Cloud growth, margins, cRPO.",
 thesis="CRM incumbent betting the platform on agentic AI monetization.",
 esg="Strong ESG/stakeholder positioning; solid governance."),

dict(sector="Software", subind="Enterprise AI", name="SAP", ticker="SAP", exch="NYSE / Xetra", country="Germany", tag="Enterprise AI",
 business="Enterprise resource planning (ERP) leader; cloud (RISE/GROW) transition drives recurring revenue. AI (Joule) embedded across suite.",
 ai_role="Embeds AI (Joule copilot + business-AI) into the ERP system-of-record for the global enterprise back office.",
 markets="Large-enterprise ERP/cloud migration; AI upsell on the cloud backlog.",
 geo="Germany-HQ; truly global; strong Europe + expanding Americas/Asia.",
 deals="Cloud-ERP migration deals; hyperscaler + model partnerships; AI (Joule) rollout.",
 flows="European mega-cap cloud-transition flows; dividend + buyback; quality ownership.",
 moat="ERP lock-in + mission-critical data. Rivals: Oracle, Microsoft, Workday, ServiceNow.",
 risks="Migration execution, macro, AI-ROI proof, competition.",
 catalyst="Cloud backlog/CCB growth, Joule adoption, margins, RISE momentum.",
 thesis="The global back-office system-of-record monetizing AI at scale.",
 esg="Strong European governance/ESG; software footprint."),

dict(sector="Software", subind="Enterprise AI", name="Adobe", ticker="ADBE", exch="Nasdaq", country="USA", tag="Creative AI",
 business="Creative + document + experience software (subscriptions). Firefly generative AI monetizes across Creative Cloud.",
 ai_role="Generative-AI for creative/marketing content (Firefly) with commercial-safe models integrated into flagship apps.",
 markets="Creative professionals, marketers/enterprises and document workflows; GenAI as new monetization.",
 geo="Global; US-heavy; broad SMB-to-enterprise base.",
 deals="Firefly model partnerships; enterprise GenAI content deals; ecosystem integrations.",
 flows="High-FCF software compounder flows; buyback; AI-disruption debate drives sentiment.",
 moat="Creative-suite incumbency + brand + data. Rivals: Canva, OpenAI/image models, Figma, midjourney-type tools.",
 risks="GenAI disruption of creative tools, pricing pressure, growth deceleration, competition.",
 catalyst="Firefly/AI monetization proof, net-new ARR, GenAI credits adoption, guidance.",
 thesis="Incumbent monetizing creative GenAI — while defending against AI-native disruptors.",
 esg="Content-provenance leadership (C2PA); strong governance."),

dict(sector="Software", subind="Enterprise AI", name="MongoDB", ticker="MDB", exch="Nasdaq", country="USA", tag="AI database",
 business="Developer data platform (document database, Atlas cloud). Consumption-based Atlas revenue drives growth.",
 ai_role="Operational + vector database for AI applications — stores app data and embeddings for RAG/agents.",
 markets="Developers/enterprises building modern + AI apps; Atlas consumption tied to app usage.",
 geo="US-heavy; global developer base; runs across all clouds.",
 deals="Vector-search + AI-framework integrations; hyperscaler marketplace; AI-app partnerships.",
 flows="Growth-software + consumption flows; volatile high-multiple ownership.",
 moat="Developer mindshare + flexible document model + vector. Rivals: Postgres/pgvector, hyperscaler DBs, specialized vector DBs.",
 risks="Consumption softness, competition from Postgres/hyperscalers, valuation, macro.",
 catalyst="Atlas consumption reacceleration, AI-app workloads, vector adoption, guidance.",
 thesis="A developer-favorite database positioned as the data layer for AI apps.",
 esg="Software footprint; standard governance."),

dict(sector="Software", subind="Enterprise AI", name="Confluent", ticker="CFLT", exch="Nasdaq", country="USA", tag="Streaming data",
 business="Data-streaming platform (managed Apache Kafka + Flink). Consumption + subscription revenue via Confluent Cloud.",
 ai_role="Real-time data pipelines that feed live context to AI systems/agents; streaming + stream-processing for AI.",
 markets="Enterprises needing real-time data movement; AI raising demand for fresh, streaming context.",
 geo="US-heavy; global enterprise expansion; multi-cloud.",
 deals="Flink/stream-processing rollout; AI + hyperscaler integrations; partner ecosystem.",
 flows="Growth-software + consumption-transition flows; smaller-cap volatility.",
 moat="Kafka stewardship + managed-cloud simplicity + Flink. Rivals: open-source Kafka, hyperscaler streaming, Redpanda.",
 risks="Consumption-model transition, competition, path to profitability, macro.",
 catalyst="Confluent Cloud consumption, Flink adoption, DSP/AI use-cases, margins.",
 thesis="The real-time data backbone feeding context to enterprise AI.",
 esg="Software footprint; standard governance."),

# ================= CYBERSECURITY (2) =================
dict(sector="Cybersecurity", subind="Security", name="CrowdStrike", ticker="CRWD", exch="Nasdaq", country="USA", tag="AI-native security",
 business="Cloud-native cybersecurity platform (Falcon) — endpoint, cloud, identity, SIEM. Subscription/ARR model.",
 ai_role="AI-native security using telemetry at scale for threat detection; agentic-AI SOC automation (Charlotte AI).",
 markets="Enterprise endpoint/cloud/identity security consolidation onto one platform; module land-and-expand.",
 geo="US-heavy; global enterprise + government; expanding internationally.",
 deals="Platform-consolidation deals; hyperscaler + partner integrations; tuck-in acquisitions (identity, SIEM, cloud).",
 flows="Premium SaaS-security flows; recovered ownership post-2024 outage; index inclusion.",
 moat="Single-agent platform + data-network effects. Rivals: Palo Alto, Microsoft Security, SentinelOne.",
 risks="July-2024 outage reputational overhang, rich valuation, competition, macro.",
 catalyst="Net-new ARR, module attach, Falcon Flex adoption, Charlotte AI, guidance.",
 thesis="AI-native platform leader consolidating the security stack.",
 esg="Reliability/governance scrutiny post-outage; strong disclosure otherwise."),

dict(sector="Cybersecurity", subind="Security", name="Palo Alto Networks", ticker="PANW", exch="Nasdaq", country="USA", tag="AI security",
 business="Broad cybersecurity platform: network security, cloud (Prisma) and SecOps (Cortex). Shifting to 'platformization' + ARR.",
 ai_role="Applies AI to security operations (Cortex XSIAM) and secures AI usage; consolidation via platformization.",
 markets="Enterprise network/cloud/SecOps security; platform-bundling to drive ARR/NGS.",
 geo="Global; US-heavy; large enterprise + government base.",
 deals="Platformization mega-deals; acquisitions (e.g., IBM QRadar SaaS, cloud/AI-security assets); partner ecosystem.",
 flows="Large-cap security flows; NGS-ARR-driven ownership; buyback.",
 moat="Breadth across three platforms + scale. Rivals: CrowdStrike, Fortinet, Microsoft, Zscaler.",
 risks="Platformization free-period drag, integration, competition, valuation.",
 catalyst="NGS ARR, XSIAM/Cortex adoption, platformization count, RPO, guidance.",
 thesis="The scaled multi-platform consolidator applying AI to security operations.",
 esg="Strong governance/disclosure; software footprint."),

# ================= INDUSTRIAL AI (4) =================
dict(sector="Industrial AI", subind="Automation", name="Siemens", ticker="SIE", exch="Xetra", country="Germany", tag="Industrial AI",
 business="Industrial conglomerate: automation, digital-industries software, smart infrastructure, mobility, healthcare stake. Diversified revenue.",
 ai_role="Industrial-AI + digital-twin leader (via automation + software/Mendix/Xcelerator); powers smart factories.",
 markets="Discrete/process automation, building/grid infrastructure, rail and industrial software.",
 geo="Germany-HQ; globally diversified; China/Europe/US balanced; portfolio reshaping (Healthineers, listed units).",
 deals="Industrial-AI + digital-twin partnerships (incl. NVIDIA Omniverse); software acquisitions (Altair-type); portfolio spins.",
 flows="European industrial + AI-industrial flows; dividend + buyback; SOTP/portfolio-simplification story.",
 moat="Automation installed base + industrial software + scale. Rivals: ABB, Rockwell, Schneider, Honeywell.",
 risks="Industrial/China cyclicality, execution on portfolio, FX.",
 catalyst="Digital Industries orders, industrial-AI software growth, portfolio actions, margins.",
 thesis="The broadest industrial-AI and digital-twin platform in the physical economy.",
 esg="Strong sustainability/governance; industrial-decarbonization enabler."),

dict(sector="Industrial AI", subind="Automation", name="Rockwell Automation", ticker="ROK", exch="NYSE", country="USA", tag="Smart manufacturing",
 business="Pure-play industrial automation (control systems, software, services). Hardware + software (FactoryTalk) + lifecycle services.",
 ai_role="Brings AI/analytics and digital-twin to US factory automation; reshoring + smart-manufacturing beneficiary.",
 markets="Discrete/hybrid/process manufacturing automation; US reshoring capex tailwind.",
 geo="US-centric (largest US pure-play automation); global operations; China smaller.",
 deals="Software/AI partnerships (NVIDIA, PTC, Microsoft); annual-recurring-revenue software push; tuck-ins.",
 flows="US-reshoring + automation flows; dividend-aristocrat ownership; cyclical rotation.",
 moat="US installed base + control-systems lock-in. Rivals: Siemens, ABB, Schneider, Emerson.",
 risks="Manufacturing PMI cyclicality, order softness, competition, execution.",
 catalyst="Order recovery, ARR/software growth, reshoring capex, margins.",
 thesis="The US pure-play on reshoring and AI-enabled smart manufacturing.",
 esg="Sustainability-in-manufacturing positioning; strong governance."),

dict(sector="Industrial AI", subind="Robotics", name="Fanuc", ticker="006954", exch="JPX", country="Japan", tag="Industrial robotics",
 business="Japanese leader in factory robots, CNC controls and robomachines. Equipment + service; highly cyclical capex-driven revenue.",
 ai_role="Core supplier of industrial robots/arms being augmented with AI vision and (future) humanoid/embodied-AI tailwinds.",
 markets="Auto, electronics and general manufacturing automation; robot demand tracks global capex + China.",
 geo="Japan-HQ; large China/US exposure; FX-sensitive; global installed base.",
 deals="AI-vision + partner integrations; capacity investments; long OEM relationships.",
 flows="Japan industrial + robotics/embodied-AI thematic flows; cash-rich balance sheet; FX-driven earnings.",
 moat="Reliability + CNC/robot installed base + service. Rivals: ABB, KUKA/Midea, Yaskawa, Kawasaki.",
 risks="Capex cyclicality, China demand, FX, competition from lower-cost robots.",
 catalyst="Global automation capex turn, China recovery, robot orders, humanoid/embodied-AI narrative.",
 thesis="Blue-chip robotics proxy levered to automation capex and embodied-AI optimism.",
 esg="Conservative Japanese governance; energy-efficient product focus."),

dict(sector="Industrial AI", subind="Robotics", name="Symbotic", ticker="SYM", exch="Nasdaq", country="USA", tag="Warehouse automation",
 business="AI-powered warehouse-automation systems (robots + software) for supply chains. System-deployment + recurring software revenue.",
 ai_role="Deploys autonomous robotic warehouse systems with AI orchestration; embodied-AI in logistics.",
 markets="Retail/wholesale distribution automation; large-customer system roll-outs drive backlog.",
 geo="US-centric; concentrated customer base (Walmart-anchored); expanding.",
 deals="Anchor Walmart relationship + JV (GreenBox/warehouse-as-a-service); new customer additions.",
 flows="High-beta robotics/AI flows; backlog-conversion + customer-concentration sensitivity; volatile.",
 moat="Integrated robotics + AI software system + large backlog. Rivals: Dematic/KION, Honeywell Intelligrated, AutoStore.",
 risks="Customer concentration (Walmart), deployment execution, margins, accounting scrutiny history.",
 catalyst="Backlog conversion, new customers, GreenBox ramp, margin/deployment milestones.",
 thesis="Pure-play on AI-driven warehouse automation — high growth, high concentration.",
 esg="Governance/customer-concentration flags; efficiency benefits to customers."),

# ================= MOBILITY AI (2) =================
dict(sector="Mobility AI", subind="Autonomous Driving", name="Tesla", ticker="TSLA", exch="Nasdaq", country="USA", tag="AI mobility",
 business="EV maker + energy storage, with autonomy (FSD/robotaxi), AI compute (Dojo) and humanoid (Optimus) optionality. Auto is the base.",
 ai_role="Real-world AI at scale — vision-based autonomy, robotaxi ambitions, custom AI training (Dojo) and humanoid robotics.",
 markets="Global EVs, energy storage, and (future) autonomy/robotaxi + robotics as the valuation swing factors.",
 geo="Global; US/China/Europe manufacturing + sales; China is both a big market and a competitive threat.",
 deals="FSD licensing talks; energy-storage megadeals; AI-compute build-out; supplier/partner network.",
 flows="Mega-cap retail + thematic AI/robotics flows; extreme sentiment-driven volatility.",
 moat="Data/scale in real-world autonomy + vertical integration + brand. Rivals: BYD/legacy autos, Waymo, other AV/robotics.",
 risks="Auto-margin pressure, autonomy timelines/regulation, China competition, valuation, key-person risk.",
 catalyst="Robotaxi rollout, FSD progress/licensing, Optimus milestones, delivery/margin trends, energy growth.",
 thesis="An auto business priced as a real-world-AI and robotics platform — thesis hinges on autonomy delivery.",
 esg="EV/clean-energy positive; governance/key-person and labor scrutiny."),

dict(sector="Mobility AI", subind="Autonomous Driving", name="Mobileye", ticker="MBLY", exch="Nasdaq", country="Israel", tag="ADAS",
 business="Vision-based ADAS/autonomous-driving systems (EyeQ chips + software) for automakers. Chip + software revenue per vehicle.",
 ai_role="Leading supplier of AI vision chips/software for driver assistance and higher-autonomy platforms to global OEMs.",
 markets="Automotive ADAS/AV content; per-vehicle content growth as autonomy levels rise.",
 geo="Israel-HQ (Intel-controlled); global OEM customers; China ADAS competition intense.",
 deals="OEM design wins for EyeQ/SuperVision/Chauffeur; Intel-parent relationship; robotaxi/AV partnerships.",
 flows="AV-thematic + auto-cyclical flows; Intel-ownership overhang; smaller-cap volatility.",
 moat="EyeQ install base + vision-AI IP + OEM relationships. Rivals: NVIDIA Drive, Qualcomm, in-house OEM, Chinese ADAS.",
 risks="Auto cyclicality/inventory, China competition, design-win timing, Intel overhang.",
 catalyst="New OEM design wins, SuperVision/Chauffeur ramps, order book, auto-production trends.",
 thesis="Pure-play on rising AI-vision content per vehicle — with stiff competition.",
 esg="Safety-mission positioning; governance tied to Intel control."),

# ================= HEALTHCARE AI (5) =================
dict(sector="Healthcare AI", subind="Healthcare", name="Tempus AI", ticker="TEM", exch="Nasdaq", country="USA", tag="Precision medicine",
 business="Precision-medicine data + diagnostics: genomic testing + a large clinical/molecular data library + AI tools. Testing + data/licensing revenue.",
 ai_role="Applies AI to one of the largest clinical-genomic datasets for oncology diagnostics and drug-development insights.",
 markets="Oncology (and expanding) diagnostics + pharma data licensing; test volume + data deals drive growth.",
 geo="US-centric; pharma partners global; data-driven model.",
 deals="Pharma data/AI partnerships; acquisitions (e.g., Ambry/Deep 6-type); biopharma collaborations.",
 flows="High-growth, unprofitable healthcare-AI flows; founder-led; volatile.",
 moat="Scale of multimodal clinical-genomic data + AI. Rivals: Guardant, Foundation/Roche, Flatiron, other genomics.",
 risks="Profitability path, reimbursement, data-privacy/regulatory, competition, valuation.",
 catalyst="Test-volume growth, data/AI deal signings, margin progress, new indications.",
 thesis="A data-network play on AI in precision oncology — early and unprofitable.",
 esg="Health-data privacy governance is the key ESG axis; founder control."),

dict(sector="Healthcare AI", subind="Healthcare", name="IQVIA", ticker="IQV", exch="NYSE", country="USA", tag="Clinical AI",
 business="Healthcare data/analytics + contract research (CRO) for pharma. Tech/analytics (TAS) + clinical research (R&DS) revenue.",
 ai_role="Applies AI/analytics to vast healthcare data for trial design, real-world evidence and commercialization.",
 markets="Pharma/biotech R&D outsourcing + data analytics; biotech funding cycle drives bookings.",
 geo="Global; US/Europe heavy; worldwide clinical-trial footprint.",
 deals="Large CRO/pharma contracts; AI + data partnerships (incl. NVIDIA healthcare AI); tuck-in analytics deals.",
 flows="Healthcare-services + AI-analytics flows; buyback; quality-compounder ownership.",
 moat="Unmatched healthcare data assets + global CRO scale. Rivals: ICON, Labcorp, Veeva (data), consultancies.",
 risks="Biotech funding softness, RFP/bookings cyclicality, pricing, FX.",
 catalyst="R&DS bookings/book-to-bill, biotech funding recovery, AI-analytics growth, margins.",
 thesis="The data-and-analytics backbone applying AI across pharma R&D and commercialization.",
 esg="Health-data governance; strong disclosure; solid governance."),

dict(sector="Healthcare AI", subind="Healthcare", name="Recursion Pharmaceuticals", ticker="RXRX", exch="Nasdaq", country="USA", tag="AI drug discovery",
 business="AI-driven drug-discovery platform (biology + chemistry + automation + compute) plus a clinical pipeline. Milestone/partnership + (future) drug revenue.",
 ai_role="Techbio pioneer using massive automated experiments + AI to industrialize drug discovery; NVIDIA-backed compute.",
 markets="Pre-clinical/clinical drug pipeline + pharma platform partnerships; milestones drive value.",
 geo="US-HQ (post-Exscientia merger, UK ops); global pharma partners.",
 deals="Big-pharma AI-discovery partnerships (Roche/Genentech, Bayer, Sanofi-type); Exscientia merger; NVIDIA collaboration.",
 flows="High-risk techbio flows; cash-runway-sensitive; volatile speculative ownership.",
 moat="Integrated wet-lab data + AI-model loop at scale. Rivals: other techbios, in-house pharma AI, Schrödinger.",
 risks="Clinical-failure risk, cash burn/runway, unproven platform economics, dilution.",
 catalyst="Clinical readouts, new/expanded pharma deals, platform milestones, cash runway.",
 thesis="A high-risk, high-optionality bet on AI industrializing drug discovery.",
 esg="Research-ethics governance; speculative-stage disclosure."),

dict(sector="Healthcare AI", subind="Healthcare", name="Schrödinger", ticker="SDGR", exch="Nasdaq", country="USA", tag="Molecular simulation",
 business="Physics-based molecular-simulation software + drug-discovery platform, plus a proprietary/partnered pipeline. Software + drug-discovery + milestones.",
 ai_role="Combines physics-based simulation with ML to predict molecule properties — computational drug/materials design.",
 markets="Pharma/biotech + materials-science software customers, plus internal/partnered pipeline.",
 geo="US-HQ; global software customers + pharma partners.",
 deals="Software subscriptions with most large pharmas; collaboration + milestone deals; materials-science expansion.",
 flows="Software + biotech hybrid ownership; pipeline-optionality + cash-burn sensitivity; volatile.",
 moat="Physics-based simulation IP + software franchise. Rivals: other comp-chem tools, in-house pharma, techbios.",
 risks="Pipeline/clinical risk, lumpy milestones, biotech budgets, burn, valuation.",
 catalyst="Software ARR growth, pipeline progress/readouts, new collaborations, milestones.",
 thesis="A picks-and-shovels + optionality play on computational drug and materials design.",
 esg="Research-integrity governance; software-led footprint."),

dict(sector="Healthcare AI", subind="Healthcare", name="GE HealthCare", ticker="GEHC", exch="Nasdaq", country="USA", tag="AI diagnostics",
 business="Medical-imaging + diagnostics + care-solutions leader (post-GE spin). Equipment + recurring service/software revenue.",
 ai_role="Embeds AI into imaging (MRI/CT/ultrasound) and diagnostics for faster, smarter clinical workflows.",
 markets="Hospitals/health systems globally; imaging replacement + AI-software attach; installed-base service.",
 geo="Global; US/Europe/China balanced; large installed base worldwide (China policy a swing factor).",
 deals="AI-imaging partnerships (NVIDIA, cloud, software firms); FDA-cleared AI algorithms; service contracts.",
 flows="Med-tech quality + AI-optionality flows; dividend; post-spin re-rating story.",
 moat="Imaging installed base + service + AI software. Rivals: Siemens Healthineers, Philips, Canon Medical.",
 risks="Hospital capex cycles, China demand/policy, competition, supply chain.",
 catalyst="AI-software attach/recurring growth, China stimulus, orders/book-to-bill, margins.",
 thesis="Scaled med-imaging incumbent monetizing AI across a huge installed base.",
 esg="Access-to-care positioning; strong governance post-spin."),

# ================= CHINA AI (1) =================
dict(sector="China AI", subind="AI Platform", name="Baidu", ticker="BIDU", exch="Nasdaq / HKEX", country="China", tag="China's frontier AI platform",
 business="China search + AI cloud + autonomous driving (Apollo Go). Search ads fund AI; cloud + Ernie models + robotaxi are the AI bets.",
 ai_role="A China frontier-model developer (Ernie) with full-stack AI cloud and a leading robotaxi fleet (Apollo Go).",
 markets="China search/advertising, enterprise AI cloud, and autonomous ride-hailing; AI reshaping monetization.",
 geo="China-centric; ADR + HK listing; US-China tech tension, chip-access limits and delisting risk.",
 deals="Ernie-model + AI-cloud enterprise deals; Apollo Go robotaxi expansion; domestic chip/partner arrangements.",
 flows="Deep-value China-tech + AI-optionality flows; buyback; ADR/southbound sentiment-driven.",
 moat="Search franchise + full-stack AI + robotaxi lead in China. Rivals: Alibaba, Tencent, ByteDance, Huawei.",
 risks="China macro/regulation, chip-access constraints, ad-share loss, geopolitics, delisting.",
 catalyst="AI-cloud growth, Ernie monetization, Apollo Go scaling/economics, ad recovery, buybacks.",
 thesis="Cheap optionality on China frontier AI, cloud and robotaxi in one name.",
 esg="Governance/state-policy + data-regulation risk; robotaxi-safety positioning."),
]
