# -*- coding: utf-8 -*-
"""Seed data for the India AI-Adopter screening template (Deliverable 2).
EXAMPLES: real, documented AI initiatives at listed Indian companies (knowledge as of early 2026),
as worked qualitative rows. Financials intentionally left blank for the user.
SECTOR_MAP: analyst frame for which industries AI reshapes most over ~10 years.
All qualitative content is a starting frame, not investment advice — verify before acting.
"""

# EXAMPLES: (ticker, company, sector, industry, ai_use, ai_category, stage, upside, value_where, lever, impact10y, score, conviction, risk)
EXAMPLES = [
 ("TCS","Tata Consultancy Services","IT Services","IT Services",
  "GenAI/agentic platform (WisdomNext) + 100k+ staff trained; large book of client GenAI transformation deals.",
  "GenAI services","Scaling",
  "Reprices services from headcount to outcome/AI; huge deal pipeline as clients operationalise GenAI.",
  "New revenue lines + delivery-cost leverage","Revenue + Margin",
  "Indian IT is India's biggest AI monetiser — sells adoption to the world; risk is pricing deflation if GenAI cuts ticket sizes.",
  4,"High","GenAI could compress traditional project sizes faster than new work replaces it."),
 ("INFY","Infosys","IT Services","IT Services",
  "Infosys Topaz (GenAI services + ~12k+ enterprise-AI use cases) and internal productivity across delivery.",
  "GenAI services","Scaling",
  "Topaz-led deals + internal margin gains; positioned as go-to partner for enterprise GenAI rollout.",
  "Revenue growth + delivery efficiency","Revenue + Margin",
  "Same structural adopter-of-AI-for-the-world thesis as TCS; execution and pricing discipline decide winners.",
  4,"High","Discretionary tech spend cyclicality; GenAI pricing pressure."),
 ("LTIM","LTIMindtree","IT Services","IT Services",
  "GenAI-led offerings and internal 'BlueVerse' AI stack; hyperscaler partnerships for AI delivery.",
  "GenAI services","Scaling",
  "Mid-cap IT leverage to GenAI deal flow; faster growth beta than large caps.",
  "Revenue growth","Revenue",
  "Beneficiary of the enterprise-AI services wave; needs to defend margins.",
  4,"Medium","Client concentration; pricing/margin pressure."),
 ("PERSISTENT","Persistent Systems","IT Services","IT Services",
  "Aggressive GenAI positioning (SASVA platform), engineering-led AI delivery, strong hyperscaler alignment.",
  "AI platform/accelerator","Scaling",
  "High-growth mid-cap with credible AI-native delivery narrative.",
  "Revenue growth","Revenue",
  "Digital-engineering play riding client AI build-outs.",
  4,"Medium","Valuation rich; dependent on discretionary AI budgets."),
 ("TATAELXSI","Tata Elxsi","IT Services / Auto tech","ER&D",
  "AI engineering for ADAS/autonomous, media content-AI, and healthcare; deep design-led AI services.",
  "GenAI engineering","Scaling",
  "Pure-play design + AI R&D exposure to auto software and media AI.",
  "Revenue growth","Revenue",
  "Levered to auto software-defined-vehicle and media AI spend; client concentration a watch.",
  4,"Medium","Lumpy client spend; concentration in a few verticals."),
 ("KPITTECH","KPIT Technologies","IT Services / Auto tech","ER&D",
  "Software + AI for autonomous/ADAS and software-defined vehicles for global OEMs.",
  "ADAS/Autonomy","Scaling",
  "Structural winner if vehicles become software+AI platforms.",
  "Revenue growth","Revenue",
  "Auto is re-platforming around software & AI — KPIT is a focused pick-and-shovel.",
  4,"Medium","OEM budget cyclicality; single-vertical concentration."),
 ("HDFCBANK","HDFC Bank","Financials","Banks",
  "AI/ML across fraud, risk, collections and CX (e.g. virtual-assistant/EVA-style bots); GenAI ops pilots.",
  "Fraud/Risk ML","Scaling",
  "Cost-to-income improvement and lower credit costs from ML at massive scale.",
  "Cost-out + risk reduction","Margin",
  "Banking is a top AI-value sector: underwriting, fraud, service automation compound over a decade.",
  4,"High","Execution at scale; data/privacy & model-risk governance."),
 ("ICICIBANK","ICICI Bank","Financials","Banks",
  "AI/ML for risk, personalization and process automation; strong digital-first stack.",
  "Fraud/Risk ML","Scaling",
  "Efficiency + cross-sell uplift from data/AI across a large franchise.",
  "Cost-out + revenue","Margin + Revenue",
  "Structural banking-AI beneficiary with a strong tech culture.",
  4,"High","Model governance; competitive parity erodes edge."),
 ("SBIN","State Bank of India","Financials","Banks",
  "AI in YONO, fraud analytics, and vast branch/ops automation potential across the largest Indian bank.",
  "CX/Chatbot","Piloting",
  "Enormous cost-efficiency headroom given scale; long runway on automation.",
  "Cost-out","Margin",
  "Largest balance sheet = largest absolute AI cost-out prize, but slower adoption cadence.",
  3,"Medium","PSU pace of change; legacy systems."),
 ("BAJFINANCE","Bajaj Finance","Financials","NBFC",
  "Data/AI-driven underwriting, cross-sell and collections across a huge customer franchise.",
  "Credit underwriting","Scaling",
  "AI compounds an already data-rich lending flywheel.",
  "Revenue + risk","Revenue + Margin",
  "Consumer-lending AI edge (approval speed, risk, cross-sell) is durable if data moat holds.",
  4,"High","Credit-cycle risk; regulatory scrutiny of digital lending."),
 ("TATAMOTORS","Tata Motors","Automobiles","Passenger/Commercial Vehicles",
  "ADAS & connected features (incl. JLR), GenAI in engineering and customer experience.",
  "ADAS/Autonomy","Piloting",
  "Content-per-vehicle and software revenue rise as cars get AI features.",
  "Revenue + product","Revenue",
  "Autos shift to software-defined + assisted-driving; premiumisation via AI features.",
  3,"Medium","Cyclical demand; JLR execution; capital intensity."),
 ("M&M","Mahindra & Mahindra","Automobiles","Auto + Farm",
  "ADAS in SUVs, AI in farm-equipment advisory/precision, and AI-led CX.",
  "ADAS/Autonomy","Piloting",
  "AI features across autos + agri-tech optionality.",
  "Revenue + product","Revenue",
  "Dual auto+farm AI exposure; precision-agri a long-dated call option.",
  3,"Medium","Cyclicality across both segments."),
 ("MARUTI","Maruti Suzuki","Automobiles","Passenger Vehicles",
  "AI in manufacturing quality/vision, demand forecasting, connected-car and dealer CX.",
  "Factory vision/QC","Piloting",
  "Cost/quality gains at scale; connected-services monetisation.",
  "Cost-out + product","Margin",
  "Volume leader; AI mostly efficiency today, feature-led later.",
  3,"Medium","EV transition; competitive intensity."),
 ("RELIANCE","Reliance Industries","Conglomerate","Telecom/Retail/Energy",
  "JioBrain AI stack across Jio; AI in retail personalization/supply-chain; AI-ready data centres.",
  "AI platform/accelerator","Scaling",
  "Cross-vertical AI + AI-infra ambitions (compute/data centres) create multiple option values.",
  "Revenue + new product","Revenue",
  "Only Indian name credibly building AI infrastructure AND applying AI across telecom/retail at scale.",
  4,"High","Capital intensity; monetisation timeline uncertain."),
 ("BHARTIARTL","Bharti Airtel","Telecom","Telecom",
  "Network AI/self-optimising networks and an AI spam/fraud-call detection system deployed for users.",
  "Network optimization","Scaling",
  "Opex efficiency + differentiated customer trust (spam shield).",
  "Cost-out + CX","Margin",
  "Telecom AI = network efficiency + churn/CX; steady rather than explosive.",
  3,"Medium","Capex cycle; ARPU dependence."),
 ("APOLLOHOSP","Apollo Hospitals","Healthcare","Hospitals",
  "Clinical AI (early-warning, imaging triage) and AI-enabled digital-health (24|7) platform.",
  "AI diagnostics/Radiology","Piloting",
  "Better outcomes/throughput + digital-health monetisation.",
  "Revenue + cost-out","Revenue + Margin",
  "Healthcare AI (diagnostics, ops) is high-impact; adoption gated by regulation and clinician trust.",
  4,"Medium","Regulatory/clinical-validation pace; capex."),
 ("DRREDDY","Dr Reddy's Laboratories","Healthcare","Pharma",
  "AI in drug discovery/formulation, manufacturing analytics and commercial ops.",
  "Drug discovery","Piloting",
  "R&D productivity and manufacturing-yield gains.",
  "Cost-out + product","Margin",
  "Pharma AI accrues slowly (discovery cycles long) but manufacturing/PV gains are nearer-term.",
  3,"Medium","Regulatory; pricing pressure in generics."),
 ("ETERNAL","Eternal (Zomato)","New-age / Consumer tech","Food & Quick-commerce",
  "AI for delivery-time prediction, routing, demand forecasting and personalization across Zomato/Blinkit.",
  "Route/Logistics AI","Scaling",
  "Unit-economics improvement (delivery efficiency, basket personalization) at huge order volume.",
  "Cost-out + revenue","Margin + Revenue",
  "Consumer-internet AI directly hits contribution margin — a clean adopter story.",
  4,"Medium","Competitive intensity; profitability optics."),
 ("PAYTM","One 97 (Paytm)","New-age / Fintech","Fintech",
  "AI for risk/fraud, collections and merchant CX; internal GenAI productivity.",
  "Fraud/Risk ML","Scaling",
  "Cost discipline + risk control as the path to durable profitability.",
  "Cost-out + risk","Margin",
  "Fintech AI edge in risk/ops; regulatory overhang is the swing factor.",
  3,"Low","Regulatory history; competition."),
 ("DELHIVERY","Delhivery","Logistics","Logistics",
  "AI/ML for route optimization, address resolution, sortation and demand forecasting.",
  "Route/Fleet optimization","Scaling",
  "Network-cost leverage as AI improves fill rates and routing.",
  "Cost-out","Margin",
  "Logistics AI compounds with scale/density — structural cost-out lever.",
  3,"Medium","Volume/pricing competition; e-commerce cyclicality."),
 ("MAPMYINDIA","C.E. Info Systems (MapmyIndia)","New-age / Auto tech","Maps & Geospatial",
  "AI/ML maps, ADAS map data and geospatial analytics (Mappls) for autos and enterprises.",
  "ADAS/Autonomy","Scaling",
  "Data moat monetised via ADAS/connected-vehicle and enterprise geospatial AI.",
  "Revenue + moat","Revenue",
  "Underappreciated AI-data pick-and-shovel for Indian mobility & logistics.",
  4,"Medium","Competition from global maps; concentration."),
 ("LT","Larsen & Toubro","Industrials","Capital Goods/EPC",
  "AI in project management, design, and a growing AI/data services arm (LTIMindtree/LTTS in group).",
  "Industrial automation","Piloting",
  "Efficiency on mega-projects + group tech exposure to AI services.",
  "Cost-out + revenue","Margin + Revenue",
  "Infra/industrial AI improves execution; group also sells AI (via listed tech arms).",
  3,"Medium","Execution risk; cyclicality."),
 ("ASIANPAINT","Asian Paints","Consumer / Materials","Paints",
  "AI in demand forecasting, supply-chain optimization and colour/marketing personalization.",
  "Supply-chain","Scaling",
  "Best-in-class supply-chain AI defends margins and service levels.",
  "Cost-out","Margin",
  "Consumer-staples AI = supply-chain + marketing efficiency; incremental, durable.",
  3,"Medium","Demand slowdown; new competition."),
 ("BEL","Bharat Electronics","Defence","Defence Electronics",
  "AI in radar/surveillance, EW and defence systems; indigenous defence-AI push.",
  "Surveillance/Radar AI","Piloting",
  "Rising AI content in defence orders; indigenisation tailwind.",
  "Revenue + product","Revenue",
  "Defence AI (autonomy, surveillance, EW) is a multi-year order-book theme.",
  4,"Medium","Order lumpiness; policy dependence."),
 ("HUL","Hindustan Unilever","FMCG","FMCG",
  "AI in demand forecasting, GenAI marketing content, and supply-chain/RGM analytics.",
  "Demand forecasting","Scaling",
  "Marketing productivity + supply-chain precision across a huge portfolio.",
  "Cost-out + revenue","Margin",
  "FMCG AI is efficiency-led (marketing, supply chain, RGM); steady compounding.",
  3,"Medium","Volume growth; rural demand."),
]

# SECTOR_MAP: (sector, impact_score_1to5, primary_lever, maturity, thesis_10y, long_ideas)
SECTOR_MAP = [
 ("IT Services / ER&D",5,"Revenue + Margin","Scaling",
  "India's principal way to MONETISE global AI adoption — sells GenAI transformation to the world. Winners reprice from headcount to outcomes; losers get deflated by AI-driven productivity. Highest direct leverage, but two-sided.",
  "TCS, INFY, HCLTECH, LTIM, PERSISTENT, COFORGE, TATAELXSI, KPITTECH"),
 ("Banks",4,"Margin (cost-out + risk)","Scaling",
  "Fraud, underwriting, collections and service automation compound on huge transaction data. Cost-to-income and credit-cost gains over a decade. Adoption gated by model-risk governance.",
  "HDFCBANK, ICICIBANK, SBIN, AXISBANK, KOTAKBANK"),
 ("NBFC / Lending",4,"Revenue + Margin","Scaling",
  "Data-rich lenders get faster approvals, better risk and cross-sell. AI widens the gap between data-moat leaders and the rest.",
  "BAJFINANCE, CHOLAFIN, SHRIRAMFIN, SBICARD"),
 ("Insurance",3,"Margin","Piloting",
  "AI in underwriting, claims automation and fraud lifts loss ratios and cuts opex. Slower, regulated adoption.",
  "HDFCLIFE, SBILIFE, ICICIGI, STARHEALTH"),
 ("Automobiles / Auto-tech",4,"Revenue + Product","Piloting",
  "Vehicles re-platform around software + assisted driving; content-per-vehicle and software revenue rise. Suppliers of auto AI software are cleaner picks than OEMs.",
  "TATAMOTORS, M&M, MARUTI, TATAELXSI, KPITTECH, SONACOMS"),
 ("New-age / Consumer tech",4,"Margin + Revenue","Scaling",
  "AI hits contribution margin directly (routing, personalization, fraud, ad-tech). Clean adopter stories where AI = unit economics.",
  "ETERNAL, PAYTM, PBFINTECH, DELHIVERY, NYKAA, MAPMYINDIA"),
 ("Telecom",3,"Margin (cost-out)","Scaling",
  "Self-optimising networks, churn/CX and fraud/spam AI cut opex and lift trust. Steady, not explosive.",
  "BHARTIARTL, RELIANCE (Jio), TATACOMM"),
 ("Healthcare / Hospitals / Diagnostics",4,"Revenue + Margin","Piloting",
  "Diagnostics/imaging AI, clinical decision support and hospital ops improve throughput and outcomes. High impact, gated by regulation and clinician trust.",
  "APOLLOHOSP, MAXHEALTH, FORTIS, DRLAL, METROPOLIS"),
 ("Pharma / CRO-CDMO",3,"Margin + Product","Piloting",
  "AI in discovery/formulation is long-cycle; manufacturing analytics and pharmacovigilance pay off sooner.",
  "DRREDDY, SUNPHARMA, CIPLA, DIVISLAB, SYNGENE"),
 ("FMCG / Consumer staples",3,"Margin","Scaling",
  "Efficiency-led: demand forecasting, supply-chain, GenAI marketing and revenue-growth-management. Incremental, durable.",
  "HUL, ITC, NESTLEIND, MARICO, DABUR, TATACONSUM"),
 ("Retail / Discretionary",3,"Margin + Revenue","Piloting",
  "Personalization, retail media, inventory and store CV analytics. Value scales with omni-channel data.",
  "TRENT, DMART, TITAN, ABFRL, RELIANCE (Retail)"),
 ("Industrials / Capital goods",3,"Margin","Piloting",
  "Digital twins, predictive maintenance and CV quality control improve asset uptime and project execution. Gradual.",
  "LT, SIEMENS, ABB, CUMMINSIND, THERMAX, HAVELLS"),
 ("Defence / Aerospace",4,"Revenue + Product","Piloting",
  "Rising AI content in autonomy, surveillance, EW and drones; indigenisation + order-book tailwind. Lumpy but structural.",
  "HAL, BEL, BDL, DATAPATTNS, ZENTEC, PARAS"),
 ("Energy / Power / Utilities",3,"Margin","Piloting",
  "Grid optimization, predictive maintenance, and AI-ready data-centre demand (a second-order power theme).",
  "NTPC, POWERGRID, TATAPOWER, RELIANCE, ADANIENSOL"),
 ("Metals / Mining / Cement",2,"Margin","Piloting",
  "Process/yield optimization, digital twins and CV safety. Efficiency gains real but commodity cycle dominates the stock.",
  "TATASTEEL, JSWSTEEL, HINDALCO, ULTRACEMCO, SHREECEM"),
 ("Chemicals",2,"Margin","Exploring",
  "Process optimization and R&D analytics; early and incremental for most Indian players.",
  "PIDILITIND, SRF, UPL, DEEPAKNTR, TATACHEM"),
 ("Logistics / Transport / Aviation",3,"Margin","Scaling",
  "Route/fleet optimization, sortation, and airline revenue-management/ops. Cost-out compounds with density.",
  "DELHIVERY, CONCOR, INDIGO, BLUEDART"),
 ("Real estate / Infra",2,"Margin","Exploring",
  "Proptech, construction-tech and smart-building analytics are early; impact modest near-term.",
  "DLF, GODREJPROP, LODHA, OBEROIRLTY, PHOENIXLTD"),
 ("Capital-markets infra / Fintech",3,"Margin + Moat","Piloting",
  "Surveillance, KYC/onboarding, robo-advisory and fraud. Data-heavy, regulated, sticky.",
  "BSE, CDSL, CAMS, ANGELONE, KFINTECH"),
]
